language: ruby
before_install:
  - gem install bundler

rvm:
  - 2.0.0

script: 'CODECLIMATE_REPO_TOKEN=d071745603653782b4edb3d07cc770b1601d29abff1c2cc6bd0ece36bc4f4ab2 bundle exec rake'

notifications:
  email:
    recipients:
      - tanay@genii.in
    on_failure: change
    on_success: never